### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by berdal84** [john-chapman/GfxSampleFramework#35]
Hi, Is there any chance to get this framework to work under linux ? Regards. B.

**Comment by john-chapman** [comment]
It's certainly possible - platform-specific source code is already separated (both in GfxSampleFramework and ApplicationTools) in `src/win`, so in theory making it work on linux should just be a matter of writing equivalent implementations for this stuff in `src/linux`, then pointing the build system to this directory instead of the Windows one.

ApplicaitonTools should be easy to convert as the platform-specific code is just the file and time functions. There is also `APT_PLATFORM_ASSERT` which wraps `GetLastError()` on Windows, not sure what the linux equivalent is.

GfxSampleFramwork will be a little more difficult as the GlContext and Window code is less straightforward. The Input code is also pretty complicated/ugly, but I have the impression that this will be easier to implement on linux, again not sure about that.

For me, cross-platform support is interesting but quite low priority since I'm only working on Windows. Of course, If someone wants to use the libs on another platform they're welcome to work on it! 😺

**Comment by berdal84** [comment]
Great. I'll start with ApplicationTools.

**Comment by john-chapman** [comment]
Bonne chance! Keep me updated with your progress; I'll create a branch `linux` to which you can submit pull requests as you work on it.

**Comment by berdal84** [comment]
Thanks !
